# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https:/ithub.com/actions/labeler

name: Labeler
on:
  pull_request:
    types: [review_requested]
jobs:
  review_requested:
    if: github.event.action == 'review_requested'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Actions Ecosystem Add Labels
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: |
            Status: Awaiting Review
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Actions Ecosystem Remove Labels
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: |
            Status: Changes Requested
            Status: Ready to Merge
